# backup interval in days
backupDayInterval : 7
# back time should in 24h format and not contains seconds (threshold is 30min) e.g: 23:00
backupTime : '04:30'
PostgreSQLBackupEnabled : true
# if backup cassandra set to true thingsboard should turn off until backup completed.
cassandraBackupEnabled : true
#If Turn Off Save Local the backup file do'nt save on this pc !!!!!
saveLocalBackup :
  enabled : true
  # location should a folder. should start and end with / (fully absolute path)
  location: "/root/thingsboardBackup/"
  #save count is number of maximum backups that store in folder
  maximumBackupsCount : 4

saveFTPBackup :
  enabled : true
  userName : 'FTPUserName'
  password : 'FTPPassword'
  address : 'ftp.address.com'
  port : 21
  # location should a folder. should start and end with /
  location: "/thingsboardBackup/"
  #save count is number of maximum backups that store in FTP
  maximumBackupsCount : 3
  # the maximum time that trasnfer file from local to ftp server (3s -> 3seconds, 5m -> 5 minutes, 1h -> 1 hour)def:20m
  transferTimeout: 20m
  # number of retry if can't save file on ftp location
  retry:
    # number of retry if can't save file on ftp location
    count : 40
    # minutes to wait between each retry
    wait: 1

